package content;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.*;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matheus
 */
public class JFEmpresas extends javax.swing.JFrame {

    /**
     * Creates new form JFEmpresas
     */
    public JFEmpresas() {
        initComponents();
    }

    private int ini = 0;
    private int fin = 4;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campos = new javax.swing.JPanel();
        cEmpresa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nEmpresa = new javax.swing.JTextField();
        cnpj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botoes = new javax.swing.JPanel();
        jBblank = new javax.swing.JButton();
        jBsave = new javax.swing.JButton();
        jBtrash = new javax.swing.JButton();
        jBrefresh = new javax.swing.JButton();
        jBsearch = new javax.swing.JButton();
        jBsArrLeft = new javax.swing.JButton();
        jBarrLeft = new javax.swing.JButton();
        jBarrRight = new javax.swing.JButton();
        jBsArrRight = new javax.swing.JButton();
        dados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEmpresaActionPerformed(evt);
            }
        });

        jLabel1.setText("Código Empresa");

        jLabel2.setText("Nome da empresa");

        nEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nEmpresaActionPerformed(evt);
            }
        });

        cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjActionPerformed(evt);
            }
        });

        jLabel3.setText("CNPJ");

        rSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSocialActionPerformed(evt);
            }
        });

        jLabel4.setText("Razão social");

        javax.swing.GroupLayout camposLayout = new javax.swing.GroupLayout(campos);
        campos.setLayout(camposLayout);
        camposLayout.setHorizontalGroup(
            camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nEmpresa)
                    .addComponent(cEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(camposLayout.createSequentialGroup()
                        .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(camposLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4))
                            .addGroup(camposLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        camposLayout.setVerticalGroup(
            camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camposLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(cEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(camposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBblank.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBblank.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBblank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/blank-ico.png"))); // NOI18N
        jBblank.setBorderPainted(false);
        jBblank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBblankActionPerformed(evt);
            }
        });

        jBsave.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBsave.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/save-ico.png"))); // NOI18N
        jBsave.setBorderPainted(false);
        jBsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaveActionPerformed(evt);
            }
        });

        jBtrash.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBtrash.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBtrash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/trash-ico.png"))); // NOI18N
        jBtrash.setBorderPainted(false);
        jBtrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtrashActionPerformed(evt);
            }
        });

        jBrefresh.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBrefresh.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/refresh-ico.png"))); // NOI18N
        jBrefresh.setBorderPainted(false);
        jBrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrefreshActionPerformed(evt);
            }
        });

        jBsearch.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBsearch.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/search-ico.png"))); // NOI18N
        jBsearch.setBorderPainted(false);
        jBsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchActionPerformed(evt);
            }
        });

        jBsArrLeft.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBsArrLeft.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBsArrLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/left-sarrow-ico.png"))); // NOI18N
        jBsArrLeft.setBorderPainted(false);
        jBsArrLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBsArrLeftMouseClicked(evt);
            }
        });
        jBsArrLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsArrLeftActionPerformed(evt);
            }
        });

        jBarrLeft.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBarrLeft.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBarrLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/left-arrow-ico.png"))); // NOI18N
        jBarrLeft.setBorderPainted(false);
        jBarrLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBarrLeftMouseClicked(evt);
            }
        });
        jBarrLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarrLeftActionPerformed(evt);
            }
        });

        jBarrRight.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBarrRight.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBarrRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/right-arrow-ico.png"))); // NOI18N
        jBarrRight.setBorderPainted(false);
        jBarrRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBarrRightMouseClicked(evt);
            }
        });
        jBarrRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarrRightActionPerformed(evt);
            }
        });

        jBsArrRight.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBsArrRight.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        jBsArrRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/right-sarrow-ico.png"))); // NOI18N
        jBsArrRight.setBorderPainted(false);
        jBsArrRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBsArrRightMouseClicked(evt);
            }
        });
        jBsArrRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsArrRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoesLayout = new javax.swing.GroupLayout(botoes);
        botoes.setLayout(botoesLayout);
        botoesLayout.setHorizontalGroup(
            botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesLayout.createSequentialGroup()
                .addComponent(jBblank, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtrash, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsArrLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBarrLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBarrRight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsArrRight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        botoesLayout.setVerticalGroup(
            botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesLayout.createSequentialGroup()
                .addGroup(botoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBblank, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtrash, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsArrLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBarrLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBarrRight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsArrRight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome do dependente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout dadosLayout = new javax.swing.GroupLayout(dados);
        dados.setLayout(dadosLayout);
        dadosLayout.setHorizontalGroup(
            dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dadosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dadosLayout.setVerticalGroup(
            dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dadosLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpar() {
        cEmpresa.setText("");
        nEmpresa.setText("");
        cnpj.setText("");
        rSocial.setText("");
    }
    
    public void atualizarDados() {
        // Pesquisando valores do banco de dados
        Connection con = Conexao.abrirConexao();
        
        EmpresaDAO cd = new EmpresaDAO(con);
        
        List<EmpresaBean> listaEmpresa = new ArrayList<EmpresaBean>();
        
        listaEmpresa = cd.listarTodos();
        
        DefaultTableModel tbm = (DefaultTableModel) jTable1.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        if (fin >= listaEmpresa.size()) {
            fin = listaEmpresa.size();
            ini = listaEmpresa.size() - 5;
        }
        for (EmpresaBean cb : listaEmpresa) {
            if (listaEmpresa.indexOf(cb) >= ini && listaEmpresa.indexOf(cb) <= fin) {
                tbm.addRow(new String[1]);
                jTable1.setValueAt(cb.getCodigo(), i, 0);
                jTable1.setValueAt(cb.getRazaoSocial(), i, 1);

                i++;
            }
        }
        
        Conexao.fecharConexao(con);
        

    }
    
    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjActionPerformed

    private void cEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmpresaActionPerformed

    private void nEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nEmpresaActionPerformed

    private void rSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSocialActionPerformed

    private void jBblankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBblankActionPerformed
        limpar();
    }//GEN-LAST:event_jBblankActionPerformed

    private void jBsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaveActionPerformed
        Connection con = Conexao.abrirConexao();
        EmpresaBean cb = new EmpresaBean();
        EmpresaDAO cd = new EmpresaDAO(con);
        
        cb.setCodigo(cEmpresa.getText());
        cb.setNomeEmpresa(nEmpresa.getText());
        cb.setCnpj(cnpj.getText());
        cb.setRazaoSocial(rSocial.getText());
        JOptionPane.showMessageDialog(null, cd.inserirEmpresa(cb));
        
        Conexao.fecharConexao(con);
    }//GEN-LAST:event_jBsaveActionPerformed

    private void jBtrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtrashActionPerformed
        Connection con = Conexao.abrirConexao();
        
        EmpresaBean cb = new EmpresaBean();
        EmpresaDAO cd = new EmpresaDAO(con);
        
        cb.setCodigo(cEmpresa.getText());

        //Cria um vetor de Objetos passando a opção de sim ou não
        Object[] opcoes = {"Sim", "Não"};
        
        int i = JOptionPane.showOptionDialog(
                null,
                "Deseja excluir esse úsuario: " + rSocial.getText() + "?",
                "Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]);
        
        if (i == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, cd.excluirEmpresa(cb));
            atualizarDados();
        }
        
        Conexao.fecharConexao(con);
    }//GEN-LAST:event_jBtrashActionPerformed

    private void jBrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrefreshActionPerformed
        // Alterando valores no banco de dados
        Connection con = Conexao.abrirConexao();
        
        EmpresaBean cb = new EmpresaBean();
        EmpresaDAO cd = new EmpresaDAO(con);
        
        cb.setCodigo(cEmpresa.getText());
        cb.setNomeEmpresa(nEmpresa.getText());
        cb.setCnpj(cnpj.getText());
        cb.setRazaoSocial(rSocial.getText());
       
        JOptionPane.showMessageDialog(null, cd.alterarEmpresa(cb));
        atualizarDados();
        Conexao.fecharConexao(con);
    }//GEN-LAST:event_jBrefreshActionPerformed

    private void jBsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchActionPerformed
        atualizarDados();
    }//GEN-LAST:event_jBsearchActionPerformed

    private void jBsArrLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsArrLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsArrLeftActionPerformed

    private void jBarrLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarrLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBarrLeftActionPerformed

    private void jBarrRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarrRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBarrRightActionPerformed

    private void jBsArrRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsArrRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsArrRightActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Connection con = Conexao.abrirConexao();
        EmpresaDAO cd = new EmpresaDAO(con);
        int selectedR = jTable1.getSelectedRow();
        EmpresaBean listaEmpresa = cd.listarTodos().get(selectedR);
        cEmpresa.setText(""+listaEmpresa.getCodigo());
        nEmpresa.setText(listaEmpresa.getNomeEmpresa());
        cnpj.setText(listaEmpresa.getCnpj());
        rSocial.setText(listaEmpresa.getRazaoSocial());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBsArrLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsArrLeftMouseClicked
        ini = 0;
        fin = 4;
        atualizarDados();
    }//GEN-LAST:event_jBsArrLeftMouseClicked

    private void jBsArrRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsArrRightMouseClicked
        fin = 100000;
        atualizarDados();
    }//GEN-LAST:event_jBsArrRightMouseClicked

    private void jBarrLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBarrLeftMouseClicked
        ini = ini - 4;
        fin = ini + 4;
        if (ini < 0 || fin < 4) {
            ini = 0;
            fin = 4;
        }
        atualizarDados();
    }//GEN-LAST:event_jBarrLeftMouseClicked

    private void jBarrRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBarrRightMouseClicked
        ini = ini + 4;
        fin = fin + 4;
        atualizarDados();
    }//GEN-LAST:event_jBarrRightMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmpresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmpresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoes;
    private javax.swing.JTextField cEmpresa;
    private javax.swing.JPanel campos;
    private javax.swing.JTextField cnpj;
    private javax.swing.JPanel dados;
    private javax.swing.JButton jBarrLeft;
    private javax.swing.JButton jBarrRight;
    private javax.swing.JButton jBblank;
    private javax.swing.JButton jBrefresh;
    private javax.swing.JButton jBsArrLeft;
    private javax.swing.JButton jBsArrRight;
    private javax.swing.JButton jBsave;
    private javax.swing.JButton jBsearch;
    private javax.swing.JButton jBtrash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nEmpresa;
    private javax.swing.JTextField rSocial;
    // End of variables declaration//GEN-END:variables
}
